// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://txkmlndovpkvwzvgkgsc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR4a21sbmRvdnBrdnd6dmdrZ3NjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMDM0MTQsImV4cCI6MjA3MTg3OTQxNH0.JYYsAjB8Pp-A3M8HSKtUMOfGzM0BBL0s6s_oERiiWR0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});